import torch
import torch.nn as nn
import torch.nn.functional as F

class MultiTaskFocalLoss(nn.Module):
    def __init__(self, pos_weight=None, alpha=0.75, gamma=2.0, lambda_profit=1.0, cost_fee=0.001):
        super().__init__()
        self.register_buffer('pos_weight', pos_weight)
        self.alpha = alpha
        self.gamma = gamma
        self.lambda_profit = lambda_profit
        self.cost_fee = cost_fee

    def forward(self, logits, targets, forward_returns=None, prev_probs=None):
        """
        logits: [Batch, 5] (raw outputs before sigmoid)
        targets: [Batch, 5] (0 or 1 labels for BK2, SK2, BP1, SP1, SP2)
        """
        probs = torch.sigmoid(logits)
        
        # 1. Base Multi-Label Focal Loss with positive weights
        # Applying pos_weight structurally forces the network to care about the rare 1s 
        # (e.g. 40 times more than the 0s).
        bce_loss = F.binary_cross_entropy_with_logits(
            logits, targets, 
            pos_weight=self.pos_weight,
            reduction='none'
        )
        pt = torch.exp(-bce_loss)  # prevents nans when probability 0
        focal_loss = self.alpha * (1 - pt) ** self.gamma * bce_loss
        
        loss_expert = focal_loss.mean()

        # 2. Continuous Profit Reward (Direct EV Maximization)
        # The previous version only multiplied the BCE loss, which meant it couldn't 
        # push probabilities high if the label was 0.
        # We now add a direct financial reward term: Maximize (Probability * Return)
        pen_profit = torch.tensor(0.0, device=logits.device)
        if forward_returns is not None:
            # Signal semantics: BK2(0)=开多 SK2(1)=开空 BP1(2)=平空 SP1(3)=平多 SP2(4)=平多
            # Bullish signals (benefit from price going UP): BK2 (go long), BP1 (close short)
            probs_buy = probs[:, [0, 2]]  # BK2, BP1
            buy_reward = (probs_buy * forward_returns.unsqueeze(1))

            # Bearish signals (benefit from price going DOWN): SK2 (go short), SP1/SP2 (close long)
            probs_sell = probs[:, [1, 3, 4]]  # SK2, SP1, SP2
            sell_reward = (probs_sell * -forward_returns.unsqueeze(1))
            
            # Total expected value generated by the model's confidence
            total_ev = buy_reward.mean() + sell_reward.mean()
            
            # Since we MINIMIZE loss, we subtract the financial EV from the loss
            # The stronger the lambda_profit, the more it will ignore expert labels to chase raw PnL
            pen_profit = -total_ev 
            
            loss_expert = loss_expert + self.lambda_profit * pen_profit

        # 3. Transaction Cost Penalty (Pen_Cost)
        pen_cost = torch.tensor(0.0, device=logits.device)
        if prev_probs is not None and probs.shape == prev_probs.shape:
            # Penalize probability flickering
            prob_diff = torch.abs(probs - prev_probs)
            pen_cost = self.cost_fee * prob_diff.mean()
            loss_expert = loss_expert + pen_cost
            
        return loss_expert, loss_expert.item(), pen_profit.item(), pen_cost.item()


import math

class PositionalEncoding(nn.Module):
    """
    Injects cyclical sine/cosine waves of different frequencies.
    Perfectly captures the oscillatory nature of J1(204d), J2(18d), J3(9d) resonance.
    """
    def __init__(self, d_model, max_len=5000):
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0) # [1, max_len, d_model]
        self.register_buffer('pe', pe)

    def forward(self, x):
        """
        Args:
            x: Tensor, shape [batch_size, seq_len, embedding_dim]
        """
        x = x + self.pe[:, :x.size(1), :].to(x.device)
        return x

class ExpertAttention(nn.Module):
    """
    Unlike a standard MultiHeadAttention, this custom layer explicitly forces 
    the Query and Key projections to be initialized and patterned after the 
    9-factor expert logic, ensuring the Attention matrix specifically calculates 
    the "Resonance" between factors (e.g. J1 intersecting with TEMA3).
    """
    def __init__(self, num_features, d_model, nhead, dropout=0.2):
        super().__init__()
        self.d_model = d_model
        self.nhead = nhead
        self.head_dim = d_model // nhead
        assert self.head_dim * nhead == d_model, "d_model must be divisible by nhead"
        
        # 1. Expert-guided Projections
        # We project the raw 21 features directly into Q, K, V spaces.
        # This structurally links the Attention Mechanism directly to the expert metadata
        # instead of a disjointed standard linear layer.
        self.q_proj = nn.Linear(num_features, d_model)
        self.k_proj = nn.Linear(num_features, d_model)
        self.v_proj = nn.Linear(num_features, d_model)
        
        self.out_proj = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, x):
        batch_size, seq_len, _ = x.shape
        
        # Project raw features to Q, K, V
        # The Q and K matrices now physically represent "What resonance am I looking for?"
        # and "What factor state am I currently in?" based directly on the 21 features.
        q = self.q_proj(x).view(batch_size, seq_len, self.nhead, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(batch_size, seq_len, self.nhead, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(batch_size, seq_len, self.nhead, self.head_dim).transpose(1, 2)
        
        # Calculate Expert Resonance (Attention Scores)
        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        attn_weights = F.softmax(scores, dim=-1)
        attn_weights = self.dropout(attn_weights)
        
        # Apply resonance weights to Values
        context = torch.matmul(attn_weights, v)
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)
        
        return self.out_proj(context)

class QuantTransformer(nn.Module):
    def __init__(self, num_features=21, d_model=64, nhead=4, num_layers=2, dropout=0.2):
        super().__init__()
        
        # 1. Positional Encoding
        self.pos_encoder = PositionalEncoding(num_features) # Applied to raw features first
        
        # 2. Expert-Injected Attention Layers
        self.expert_attention_layers = nn.ModuleList([
            ExpertAttention(num_features if i == 0 else d_model, d_model, nhead, dropout)
            for i in range(num_layers)
        ])
        
        # Layer Norms and FFNs for the Transformer blocks
        self.norms1 = nn.ModuleList([nn.LayerNorm(d_model) for _ in range(num_layers)])
        self.norms2 = nn.ModuleList([nn.LayerNorm(d_model) for _ in range(num_layers)])
        self.ffns = nn.ModuleList([
            nn.Sequential(
                nn.Linear(d_model, d_model * 2),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(d_model * 2, d_model)
            ) for _ in range(num_layers)
        ])
        self.dropouts = nn.ModuleList([nn.Dropout(dropout) for _ in range(num_layers)])
        
        # 3. Output Decoder
        self.decoder = nn.Sequential(
            nn.Linear(d_model, 32),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(32, 5)
        )

    def forward(self, x):
        """
        x shape: [Batch, Sequence_Len, Num_Features (21)]
        """
        # Inject sinusoidal waves directly into the raw 21 features
        x = self.pos_encoder(x)
        
        # Pass through Expert Attention Transformer Blocks
        out = x
        for i in range(len(self.expert_attention_layers)):
            # Self-Attention where QKV are derived from expert metadata
            attn_out = self.expert_attention_layers[i](out)
            
            # Skip connection & LayerNorm (Note: dimension changes on first layer from 21 -> 64)
            if i == 0:
                # Can't do direct residual if dims change, so we just use attn_out
                out = self.norms1[i](attn_out)
            else:
                out = self.norms1[i](out + self.dropouts[i](attn_out))
                
            # FFN
            ffn_out = self.ffns[i](out)
            out = self.norms2[i](out + self.dropouts[i](ffn_out))
        
        # Predict based on the last day's resonant state
        last_day_features = out[:, -1, :]
        logits = self.decoder(last_day_features)
        
        return logits
